# Sql Analysis for Programmers/Developers

Analysis questions
Data Analysis
1. Impact of region on salary - Raphael
2. How does level of education affect the salary -  Norah
3. Years of experience in relation to salary - Alex
4. Organization Size in relation to salary - Joseph
5. Impact of Job title to salary - Wanjiru 
6. Impact of gender on Salary - Norah
7. Types of skills possesed and how it affects the salary - Joseph
8. impact of sexuality on salary- Alex
9. impact of ethnicity on salary - Wanjiru

In [ ]:
#We will first load our sql extension into the environment
%load_ext sql

#We will then connect to our memory sqlite database
%sql sqlite://

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: @None'

## Loading Our dataset in our environment

In [ ]:
# Importing pandas into our env
import pandas as pd 
import csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Loading our filtered survey dataset 
survey = pd.read_csv("survey-results-filtered.csv")
survey.head(5)

#importing our table into the sql env
%sql DROP Table IF EXISTS survey
%sql Persist survey;

#Selecting data from our sql table
%sql Select * from Survey limit 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[(0, 7, 'I am a developer by profession', 'Yes', 36.0, '12', 'Yearly', 116000.0, 'United States', 'MariaDB;MySQL;Redis', 'Developer, back-end;Developer, desktop or enterprise applications;Developer, game or graphics', 'Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)', 'Employed full-time', 'White or of European descent', 'Man', 'Remote work options;Opportunities for professional development;Family friendliness', 'Slightly dissatisfied', 'Python;SQL', 'Confluence;Jira;Github;Slack;Microsoft Teams;Google Suite (Docs, Meet, etc)', 'Not at all important/not necessary', 'Once a year', 'No', 'Occasionally: 1-2 days per quarter but less than monthly', 'Linux-based', '20 to 99 employees', 'Docker', 'I have some influence', 'Straight / Heterosexual', 'Yes', 'No, not really', 'Less than once per month or monthly', 'Multiple times per day', 'No', 'Computer science, computer engineering, or software engineering', 'Django;React.js;Vue.js', 'Flask', 'Just as welcome now as I felt last year', 39.0, '17', '13'),
 (1, 9, 'I am a developer by profession', 'Yes', 22.0, '14', 'Yearly', 32315.0, 'United Kingdom', 'Microsoft SQL Server', 'Database administrator;Developer, full-stack;Developer, mobile', 'Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)', 'Employed full-time', 'White or of European descent', 'Man', 'Flex time or a flexible schedule;How widely used or impactful my work output would be;Opportunities for professional development', 'Very satisfied', 'HTML/CSS;Java;JavaScript;Python;SQL', 'Github;Microsoft Teams', 'Fairly important', 'Every few months', 'No', 'Often: 1-2 days per week or more', 'Windows', '2 to 9 employees', 'Android;Linux;Raspberry Pi;Windows', 'I have a great deal of influence', 'Straight / Heterosexual', 'Yes', 'Yes, definitely', 'Multiple times per day', 'Multiple times per day', 'No', 'Mathematics or statistics', 'Flask;jQuery', 'Flask;jQuery', 'Somewhat more welcome now than last year', 36.0, '8', '4'),
 (2, 10, 'I am a developer by profession', 'Yes', 23.0, '13', 'Yearly', 40070.0, 'United Kingdom', 'Firebase;MongoDB;PostgreSQL;SQLite', 'Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end', 'Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)', 'Employed full-time', 'White or of European descent', 'Man', 'Flex time or a flexible schedule;Languages, frameworks, and other technologies Iâ€™d be working with;Remote work options', 'Slightly dissatisfied', 'C#;JavaScript;Swift', 'Confluence;Jira;Github;Slack;Microsoft Teams;Microsoft Azure;Trello;Google Suite (Docs, Meet, etc);Stack Overflow for Teams', 'Very important', 'Every few months', 'No', 'Rarely: 1-2 days per year or less', 'Windows', '10,000 or more employees', 'AWS;Heroku;iOS', 'I have little or no influence', 'Straight / Heterosexual', 'Yes', 'Yes, somewhat', 'I have never participated in Q&A on Stack Overflow', 'Multiple times per day', 'No', 'Computer science, computer engineering, or software engineering', 'Angular;Django;React.js', 'Angular;Angular.js;Django;React.js', 'Just as welcome now as I felt last year', 40.0, '10', '2'),
 (3, 11, 'I am a developer by profession', 'No', 49.0, '42', 'Monthly', 14268.0, 'Spain', '.', 'Designer;Developer, front-end', 'Some college/university study without earning a degree', 'Employed full-time', 'White or of European descent', 'Man', 'Remote work options;Office environment or company culture;Family friendliness', 'Very dissatisfied', 'HTML/CSS;JavaScript', 'Github', 'Somewhat important', 'Once every few years', 'No', 'Rarely: 1-2 days per year or less', 'Windows', '2 to 9 employees', 'Windows;WordPress', 'I have little or no influence', 'Straight / Heterosexual', 'Yes', 'Yes, somewhat', 'A few times per week', 'Multiple times per day', 'No', 'Mathematics or statistics', 'ASP.NET;jQuery', 'ASP.NET;jQuery', 'Just as welcome now as I felt last year', 40.0, '7', '7'),
 (4, 12, 'I am not primarily a developer, but I write code sometimes as part of my work', 'Yes', 53.0, '14', 'Monthly', 38916.0, 'Netherlands', '.', 'Designer;Developer, back-end', 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)', 'Employed full-time', 'White or of European descent', 'Man', 'Industry that Iâ€™d be working in;Financial performance or funding status of the company or organization;Office environment or company culture', 'Very satisfied', 'C;JavaScript;Python', '.', 'Not at all important/not necessary', 'Once every few years', 'No', 'Rarely: 1-2 days per year or less', 'MacOS', '2 to 9 employees', 'MacOS;Windows', 'I have some influence', 'Straight / Heterosexual', 'Yes', 'Yes, definitely', 'Multiple times per day', 'Multiple times per day', 'No', '.', '.', '.', 'A lot less welcome now than last year', 36.0, '35', '20')]

# **ANALYSIS SECTION**

## **Impact of region on salary**

In [ ]:
%%sql
Select Country, AVG(ConvertedComp) from survey
group by Country
Order by AVG(ConvertedComp) DESC;

 * sqlite://
Done.

[('Nomadic', 203099.4),
 ('Ireland', 182761.0),
 ('Paraguay', 169264.0),
 ('United States', 159523.58904657204),
 ('Switzerland', 150911.90688259108),
 ('Australia', 147192.8827292111),
 ('Norway', 146590.56707317074),
 ('New Zealand', 145172.42307692306),
 ('Republic of Korea', 143203.875),
 ('United Kingdom', 142433.74816625917),
 ('Andorra', 141608.0),
 ('Hong Kong (S.A.R.)', 117009.93333333333),
 ('Israel', 111229.96363636364),
 ('Canada', 109187.99642431465),
 ('Singapore', 104248.38095238095),
 ('Denmark', 101410.95679012345),
 ('Japan', 100766.59047619048),
 ('South Korea', 97223.73913043478),
 ('Germany', 90447.44371296906),
 ("Lao People's Democratic Republic", 89854.0),
 ('Costa Rica', 89693.33333333333),
 ('Bahamas', 86706.0),
 ('Kosovo', 82783.27272727272),
 ('Lebanon', 81203.64285714286),
 ('Iceland', 80200.66666666667),
 ('Belgium', 79819.75568181818),
 ('Netherlands', 78026.0),
 ('Ecuador', 77851.61904761905),
 ('France', 76679.80932203389),
 ('Austria', 75838.1),
 ('Spain', 75147.625),
 ('Italy', 72958.96371882086),
 ('Sweden', 72080.6449704142),
 ('Luxembourg', 69418.55555555556),
 ('Portugal', 67742.89032258064),
 ('Benin', 64859.0),
 ('Finland', 63252.144),
 ('China', 61795.166666666664),
 ('Taiwan', 60912.36),
 ('Zambia', 60000.0),
 ('San Marino', 59454.0),
 ('Jamaica', 57250.0),
 ('Uruguay', 56058.8),
 ('South Africa', 55929.75),
 ('Saudi Arabia', 55535.72727272727),
 ('Slovakia', 55458.26865671642),
 ('Slovenia', 53760.60655737705),
 ('El Salvador', 52400.0),
 ('Kuwait', 51324.0),
 ('Montenegro', 50472.0),
 ('United Arab Emirates', 50204.08),
 ('Turkmenistan', 50000.0),
 ('Thailand', 48264.9),
 ('Bahrain', 47740.0),
 ('Romania', 45777.76536312849),
 ('Cyprus', 44883.857142857145),
 ('Poland', 44054.7139959432),
 ('Malta', 43464.95),
 ('Malaysia', 43324.23333333333),
 ('Lithuania', 42434.32394366197),
 ('Czech Republic', 42279.29857819905),
 ('Estonia', 41769.069444444445),
 ('Greece', 40378.03937007874),
 ('Haiti', 38364.0),
 ('Ukraine', 37476.882978723406),
 ('Zimbabwe', 36674.28571428572),
 ('Armenia', 36205.89473684211),
 ('Isle of Man', 35977.333333333336),
 ('Croatia', 35685.81690140845),
 ('Qatar', 35473.0),
 ('Bulgaria', 34474.99145299145),
 ('Latvia', 34241.27777777778),
 ('Trinidad and Tobago', 34236.0),
 ('Hungary', 34218.21232876712),
 ('Argentina', 33983.56296296296),
 ('Serbia', 33607.171428571426),
 ('Rwanda', 33537.6),
 ('Belarus', 32938.545454545456),
 ('Bosnia and Herzegovina', 32742.125),
 ('Oman', 32708.0),
 ('Russian Federation', 32301.872235872237),
 ("CÃ´te d'Ivoire", 31312.0),
 ('Albania', 29536.285714285714),
 ('Chile', 29171.196721311477),
 ('Jordan', 28628.875),
 ('Namibia', 28560.0),
 ('India', 26979.672215843857),
 ('Dominican Republic', 26421.0),
 ('Turkey', 26309.689516129034),
 ('Malawi', 26220.0),
 ('Nicaragua', 25325.53846153846),
 ('Mexico', 25086.272222222222),
 ('Indonesia', 24743.258823529413),
 ('Georgia', 24341.0),
 ('Brazil', 24336.89230769231),
 ('Guatemala', 24156.352941176472),
 ('Panama', 22800.0),
 ('Honduras', 22478.666666666668),
 ('Nigeria', 21995.426966292136),
 ('Iran', 21924.677725118483),
 ('Morocco', 20698.18181818182),
 ('Viet Nam', 20601.73846153846),
 ('Uzbekistan', 20417.14285714286),
 ('Colombia', 19747.347826086956),
 ('Uganda', 19512.117647058825),
 ('Iraq', 18722.0),
 ('Maldives', 18258.0),
 ('Afghanistan', 17919.153846153848),
 ('United Republic of Tanzania', 17739.428571428572),
 ('Azerbaijan', 17572.0),
 ('Kazakhstan', 17562.65),
 ('Botswana', 17403.0),
 ('Peru', 17059.39285714286),
 ('Kenya', 16426.880952380954),
 ('The former Yugoslav Republic of Macedonia', 15339.555555555555),
 ('Cuba', 15219.0),
 ('Republic of Moldova', 15070.5),
 ('Egypt', 14793.732142857143),
 ('Somalia', 14400.0),
 ('Philippines', 14119.471264367816),
 ('Algeria', 13536.444444444445),
 ('Pakistan', 13074.53431372549),
 ('Cambodia', 12948.0),
 ('Nepal', 12927.629032258064),
 ('Madagascar', 12767.2),
 ('Bangladesh', 11683.050847457627),
 ('Sri Lanka', 11188.194805194806),
 ('Venezuela, Bolivarian Republic of...', 11027.2),
 ('Tunisia', 10809.882352941177),
 ('Mauritius', 10756.0),
 ('Bhutan', 10301.666666666666),
 ('Bolivia', 10087.0),
 ('Ghana', 9567.8),
 ('Democratic Republic of the Congo', 9054.0),
 ('Swaziland', 8820.0),
 ('Togo', 7908.0),
 ('Guinea', 7788.0),
 ('Senegal', 7110.0),
 ('Myanmar', 6363.428571428572),
 ('Ethiopia', 6166.0),
 ('Mongolia', 6096.0),
 ('Kyrgyzstan', 5071.2),
 ('Syrian Arab Republic', 4833.6),
 ('Sudan', 4312.8),
 ('Burkina Faso', 3960.0),
 ('Cameroon', 3957.6666666666665),
 ('Brunei Darussalam', 2580.0),
 ('Lesotho', 24.0)]

## **How does Level of education affect salary**

In [ ]:
%%sql
select EdLevel, AVG(ConvertedComp) from survey where CompFreq = "Monthly"
group by EdLevel
order by AVG(ConvertedComp) desc;

 * sqlite://
Done.

[('Other doctoral degree (Ph.D., Ed.D., etc.)', 168480.5194805195),
 ('Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)', 105038.34775086505),
 ('Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)', 98509.30360531309),
 ('Some college/university study without earning a degree', 75270.43046357617),
 ('.', 74046.50267379679),
 ('Associate degree (A.A., A.S., etc.)', 69982.48333333334),
 ('Primary/elementary school', 61277.555555555555),
 ('Professional degree (JD, MD, etc.)', 60913.24444444444),
 ('Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)', 59705.71760154739),
 ('I never completed any formal education', 48081.6)]

Years of experience in relation to salary

In [ ]:
%%sql
select yearscode, AVG(convertedcomp), WorkWeekHrs from survey where CompFreq = "Monthly"
group by yearscode
order by AVG(convertedcomp) desc;

 * sqlite://
Done.

[('47', 1003870.6666666666, 56.0),
 ('45', 631653.0, 50.0),
 ('38', 401918.08, 40.0),
 ('42', 399572.0, 40.0),
 ('50', 324568.0, 40.0),
 ('39', 270605.64705882355, 38.0),
 ('27', 258844.45901639343, 39.0),
 ('40', 228653.53846153847, 45.0),
 ('35', 221504.1038961039, 32.0),
 ('23', 218520.08988764044, 20.0),
 ('More than 50 years', 200763.0, 40.0),
 ('33', 200219.44827586206, 20.0),
 ('26', 196370.0338983051, 25.0),
 ('37', 189444.42857142858, 36.0),
 ('41', 184919.27272727274, 44.0),
 ('34', 170624.16, 44.0),
 ('36', 170451.29411764705, 38.0),
 ('30', 164877.2911392405, 40.0),
 ('24', 164018.78787878787, 40.0),
 ('31', 162231.85185185185, 40.0),
 ('28', 152202.84444444443, 42.0),
 ('22', 150076.928, 40.74558086354557),
 ('20', 148460.70142180094, 40.0),
 ('48', 141888.0, 40.0),
 ('19', 139439.232, 40.0),
 ('29', 138274.36363636365, 40.74558086354557),
 ('17', 132048.61878453038, 39.0),
 ('25', 125420.81767955801, 40.0),
 ('21', 117600.90909090909, 40.0),
 ('32', 105048.82352941176, 40.0),
 ('18', 103270.93333333333, 45.0),
 ('16', 102877.68421052632, 40.0),
 ('14', 102752.71523178808, 42.0),
 ('43', 102730.0, 40.0),
 ('10', 95675.93428258489, 40.0),
 ('13', 95114.9494949495, 14.0),
 ('15', 93565.38181818182, 40.0),
 ('11', 86566.58258258259, 40.0),
 ('12', 86045.86609071275, 40.0),
 ('4', 70404.4739336493, 48.0),
 ('8', 66140.12942989214, 35.0),
 ('7', 61005.044628099175, 48.0),
 ('6', 59795.743589743586, 39.0),
 ('9', 55523.70709382151, 40.0),
 ('2', 54037.52486187845, 40.0),
 ('5', 48378.68580542265, 40.0),
 ('3', 42475.41747572816, 40.0),
 ('44', 41790.0, 40.0),
 ('1', 41782.52631578947, 38.0),
 ('0', 35865.78947368421, 40.0),
 ('46', 19392.0, 45.0),
 ('Less than 1 year', 13693.636363636364, 45.0)]

##  **Organization Size in relation to salary**

In [ ]:
%%sql
select OrgSize, avg(convertedcomp) from survey where CompFreq = "Monthly"
group by OrgSize
order by avg(convertedcomp) desc;

 * sqlite://
Done.

[('10,000 or more employees', 171056.16666666666),
 ('5,000 to 9,999 employees', 134527.9477124183),
 ('1,000 to 4,999 employees', 116494.52948557089),
 ('100 to 499 employees', 102314.07843137255),
 ('500 to 999 employees', 91148.94845360825),
 ('20 to 99 employees', 88029.05706760316),
 ('.', 67754.52054794521),
 ('10 to 19 employees', 66843.08340971585),
 ('Just me - I am a freelancer, sole proprietor, etc.', 62696.3023255814),
 ('2 to 9 employees', 56990.51048951049)]

## **Impact of Job title to salary**

In [ ]:
%%sql
select DevType, country, AVG(convertedcomp), CompFreq from survey where CompFreq = "Monthly"
group by country, CompFreq
order by AVG(Convertedcomp) asc;

 * sqlite://
Done.

[('Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, mobile;Educator', 'Lesotho', 24.0, 'Monthly'),
 ('Academic researcher;Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile;DevOps specialist;Product manager', 'Brunei Darussalam', 2580.0, 'Monthly'),
 ('Data or business analyst;Database administrator;Designer;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack', 'Burkina Faso', 3960.0, 'Monthly'),
 ('Developer, back-end;Developer, mobile', 'Sudan', 4312.8, 'Monthly'),
 ('Developer, full-stack;Developer, mobile', 'Cameroon', 4416.0, 'Monthly'),
 ('Data or business analyst;Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;System administrator', 'Ethiopia', 4621.2, 'Monthly'),
 ('Developer, full-stack', 'Syrian Arab Republic', 4833.6, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, game or graphics;System administrator', 'Kyrgyzstan', 5071.2, 'Monthly'),
 ('Developer, full-stack', 'Mongolia', 6096.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end', 'Myanmar', 6363.428571428572, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Ghana', 6414.545454545455, 'Monthly'),
 ('Data or business analyst;Database administrator;Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, mobile;Engineer, data', 'Senegal', 7110.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Guinea', 7788.0, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, full-stack;Developer, mobile;System administrator', 'Togo', 7908.0, 'Monthly'),
 ('Data scientist or machine learning specialist;Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack', 'Nepal', 8360.816326530612, 'Monthly'),
 ('Data or business analyst;Engineer, data', 'Bhutan', 8448.0, 'Monthly'),
 ('Developer, full-stack', 'Nigeria', 8792.059701492537, 'Monthly'),
 ('Database administrator;Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Educator', 'Swaziland', 8820.0, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Educator;Engineering manager', 'Democratic Republic of the Congo', 9054.0, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack', 'Afghanistan', 9110.666666666666, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Bangladesh', 9540.11009174312, 'Monthly'),
 ('Academic researcher;Developer, back-end;Developer, full-stack;Developer, mobile;Developer, QA or test;DevOps specialist;Product manager;System administrator', 'Bolivia', 10087.0, 'Monthly'),
 ('Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, mobile', 'Mauritius', 10756.0, 'Monthly'),
 ('Data or business analyst;Database administrator;Developer, back-end;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, mobile;Developer, QA or test;DevOps specialist;Educator;Engineer, site reliability;System administrator', 'Tunisia', 10809.882352941177, 'Monthly'),
 ('Developer, back-end', 'United Republic of Tanzania', 10975.2, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'The former Yugoslav Republic of Macedonia', 11007.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile;System administrator', 'Sri Lanka', 11090.88, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, full-stack;Engineering manager', 'Pakistan', 11106.694736842106, 'Monthly'),
 ('Database administrator;Developer, desktop or enterprise applications', 'Venezuela, Bolivarian Republic of...', 11300.57142857143, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack', 'Philippines', 12918.648648648648, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Cambodia', 12948.0, 'Monthly'),
 ('Designer;Developer, back-end;Developer, front-end;Developer, full-stack;Engineer, site reliability', 'Algeria', 13018.285714285714, 'Monthly'),
 ('Developer, full-stack', 'Kenya', 13236.0, 'Monthly'),
 ('Data or business analyst;Data scientist or machine learning specialist;Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, mobile;Engineer, data;Engineer, site reliability;System administrator', 'Madagascar', 13689.0, 'Monthly'),
 ('Data or business analyst;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack', 'Egypt', 13819.018867924528, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'Republic of Moldova', 14345.6, 'Monthly'),
 ('Database administrator;Designer;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile;Educator', 'Somalia', 14400.0, 'Monthly'),
 ('Data scientist or machine learning specialist;Developer, full-stack', 'Guatemala', 14979.0, 'Monthly'),
 ('Developer, full-stack;Developer, game or graphics;Developer, mobile', 'Cuba', 15219.0, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;DevOps specialist;System administrator', 'Peru', 16616.869565217392, 'Monthly'),
 ('Academic researcher;Data or business analyst;Database administrator;Designer;Developer, back-end;Developer, desktop or enterprise applications;Develo ... (110 characters truncated) ... eveloper, mobile;Developer, QA or test;DevOps specialist;Engineer, data;Engineer, site reliability;Engineering manager;Scientist;System administrator', 'Nicaragua', 16839.272727272728, 'Monthly'),
 ('Developer, mobile', 'Botswana', 17403.0, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Jamaica', 17736.0, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications', 'Azerbaijan', 17833.090909090908, 'Monthly'),
 ('Developer, embedded applications or devices;Developer, mobile', 'Uganda', 17870.4, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, full-stack;Developer, mobile', 'Maldives', 18258.0, 'Monthly'),
 ('Academic researcher;Designer;Developer, front-end;Developer, mobile;Scientist;System administrator', 'Kazakhstan', 18269.052631578947, 'Monthly'),
 ('Academic researcher;Data or business analyst;Developer, back-end;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, mobile;Engineering manager;Product manager;Senior executive/VP', 'Colombia', 18492.564705882352, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;System administrator', 'Iraq', 18722.0, 'Monthly'),
 ('Developer, back-end;Developer, full-stack;DevOps specialist;System administrator', 'Viet Nam', 18942.206896551725, 'Monthly'),
 ('Academic researcher;Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, mobile;Product manager', 'Morocco', 20703.157894736843, 'Monthly'),
 ('Academic researcher;Developer, full-stack;Developer, game or graphics;DevOps specialist;Engineer, site reliability;System administrator', 'Honduras', 20718.0, 'Monthly'),
 ('Academic researcher;Developer, embedded applications or devices;Educator', 'Brazil', 21385.647819063004, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, mobile;Senior executive/VP;System administrator', 'Iran', 21943.481865284975, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'Panama', 22800.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'Georgia', 22862.823529411766, 'Monthly'),
 ('Developer, full-stack', 'Uzbekistan', 23770.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end', 'Mexico', 23940.897959183672, 'Monthly'),
 ('Developer, back-end;DevOps specialist;Engineer, site reliability;System administrator', 'Indonesia', 24902.613333333335, 'Monthly'),
 ('Data or business analyst;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, QA or test', 'Dominican Republic', 24984.48, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack', 'Qatar', 25364.0, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, full-stack;Educator', 'Montenegro', 25944.0, 'Monthly'),
 ('Academic researcher;Developer, desktop or enterprise applications;Scientist', 'Malawi', 26220.0, 'Monthly'),
 ('Developer, full-stack', 'Turkey', 26269.35135135135, 'Monthly'),
 ('Developer, back-end', 'Bosnia and Herzegovina', 26965.333333333332, 'Monthly'),
 ('Developer, front-end;Developer, full-stack', 'Jordan', 27058.4, 'Monthly'),
 ('Academic researcher;Data or business analyst;Data scientist or machine learning specialist;Scientist', 'Chile', 27838.372881355932, 'Monthly'),
 ('Academic researcher;Data scientist or machine learning specialist;Educator;Scientist', 'Namibia', 28560.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'Albania', 29536.285714285714, 'Monthly'),
 ('Data scientist or machine learning specialist', 'Hungary', 30020.492307692308, 'Monthly'),
 ('Developer, front-end', 'Belarus', 30463.846153846152, 'Monthly'),
 ('Database administrator;Developer, desktop or enterprise applications', 'Russian Federation', 31028.1935483871, 'Monthly'),
 ('Data scientist or machine learning specialist;Developer, back-end;Developer, front-end', "CÃ´te d'Ivoire", 31312.0, 'Monthly'),
 ('Data or business analyst;Developer, desktop or enterprise applications', 'Bulgaria', 31606.5, 'Monthly'),
 ('Developer, back-end;Developer, front-end', 'Argentina', 31677.6, 'Monthly'),
 ('Data scientist or machine learning specialist', 'Serbia', 31723.91489361702, 'Monthly'),
 ('Developer, back-end;Developer, full-stack', 'Oman', 32708.0, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, game or graphics', 'Croatia', 33375.51724137931, 'Monthly'),
 ('Academic researcher;Data or business analyst;Designer;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Rwanda', 33537.6, 'Monthly'),
 ('Developer, full-stack', 'Latvia', 33616.58823529412, 'Monthly'),
 ('Academic researcher;Data or business analyst;Data scientist or machine learning specialist;Developer, back-end;Developer, desktop or enterprise applications;Developer, full-stack;DevOps specialist', 'Trinidad and Tobago', 34236.0, 'Monthly'),
 ('Developer, back-end;Developer, full-stack', 'India', 34420.88947368421, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, full-stack;Engineering manager', 'Ukraine', 34666.568181818184, 'Monthly'),
 ('Developer, back-end;Developer, full-stack;DevOps specialist;Engineer, site reliability', 'Armenia', 36205.89473684211, 'Monthly'),
 ('Database administrator;Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Engineer, data;System administrator', 'Greece', 37597.166666666664, 'Monthly'),
 ('Developer, front-end;Developer, mobile;Educator', 'Haiti', 38364.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'Estonia', 39441.24590163935, 'Monthly'),
 ('Developer, back-end;Developer, full-stack', 'Czech Republic', 40270.8, 'Monthly'),
 ('Data or business analyst;Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;System administrator', 'Lithuania', 40919.81538461539, 'Monthly'),
 ('Developer, back-end', 'Romania', 42420.67924528302, 'Monthly'),
 ('Developer, full-stack;Developer, game or graphics;Scientist', 'Poland', 42487.66507177034, 'Monthly'),
 ('Academic researcher;Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, QA or test', 'Thailand', 42566.72727272727, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;System administrator', 'Malaysia', 45026.49056603773, 'Monthly'),
 ('Developer, front-end', 'Cyprus', 46431.0, 'Monthly'),
 ('Designer;Developer, front-end;System administrator', 'Zimbabwe', 47904.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Saudi Arabia', 49950.666666666664, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile;Educator;Engineering manager', 'Uruguay', 51613.09090909091, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, mobile', 'United Arab Emirates', 51728.86956521739, 'Monthly'),
 ('Designer;Developer, full-stack;Engineering manager', 'El Salvador', 52400.0, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, full-stack', 'South Africa', 54255.65562913907, 'Monthly'),
 ('Data scientist or machine learning specialist;Developer, back-end;Developer, full-stack;Senior executive/VP', 'Slovakia', 55099.32203389831, 'Monthly'),
 ('Designer;Developer, back-end;Developer, embedded applications or devices;Developer, QA or test;System administrator', 'Slovenia', 56128.8, 'Monthly'),
 ('Developer, desktop or enterprise applications;Developer, full-stack', 'Luxembourg', 57186.0, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Product manager;System administrator', 'Malta', 59676.0, 'Monthly'),
 ('Database administrator;Designer;Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;Developer, mobile;System administrator', 'Zambia', 60000.0, 'Monthly'),
 ('Developer, full-stack', 'Kuwait', 60804.0, 'Monthly'),
 ('Academic researcher;Data or business analyst;Database administrator;Developer, back-end;Engineer, data', 'Finland', 63518.52, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, embedded applications or devices;Engineer, site reliability', 'China', 63948.0, 'Monthly'),
 ('Developer, back-end', 'Hong Kong (S.A.R.)', 70039.30434782608, 'Monthly'),
 ('Developer, back-end;Developer, embedded applications or devices', 'Sweden', 72905.90277777778, 'Monthly'),
 ('Developer, desktop or enterprise applications', 'Taiwan', 74520.0, 'Monthly'),
 ('Developer, full-stack', 'Belgium', 75120.80597014926, 'Monthly'),
 ('Developer, full-stack;Developer, mobile;Developer, QA or test', 'Ecuador', 76930.73684210527, 'Monthly'),
 ('Developer, game or graphics', 'Portugal', 78021.78217821782, 'Monthly'),
 ('Designer;Developer, front-end', 'Netherlands', 78936.66396761134, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack;Developer, game or graphics;Developer, mobile', 'Iceland', 80721.81818181818, 'Monthly'),
 ('Developer, full-stack', 'Austria', 84007.70370370371, 'Monthly'),
 ('Database administrator;Designer;Developer, back-end;Developer, front-end;Developer, full-stack;DevOps specialist;Educator;Senior executive/VP;System administrator', 'Bahamas', 86412.0, 'Monthly'),
 ('Academic researcher;Data or business analyst;Data scientist or machine learning specialist;Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, full-stack;Developer, mobile;Educator;Engineer, data', 'Kosovo', 92892.0, 'Monthly'),
 ('Developer, back-end;Developer, full-stack;DevOps specialist', 'Denmark', 98906.09523809524, 'Monthly'),
 ('Data or business analyst;Developer, desktop or enterprise applications;Developer, embedded applications or devices;Developer, front-end;Developer, full-stack', 'Lebanon', 100395.6, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack;Developer, mobile', 'Costa Rica', 104316.26666666666, 'Monthly'),
 ('Developer, desktop or enterprise applications;Developer, full-stack', 'Singapore', 107352.17777777778, 'Monthly'),
 ('Developer, back-end', 'Israel', 107927.6, 'Monthly'),
 ('Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;Developer, game or graphics;Developer, mobile;Senior executive/VP;System administrator', 'Italy', 111531.4491017964, 'Monthly'),
 ('Developer, front-end;Developer, mobile', 'France', 116855.42857142857, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack;DevOps specialist', 'Germany', 120605.56678700361, 'Monthly'),
 ('Developer, full-stack', 'Japan', 152685.7, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'South Korea', 156577.14285714287, 'Monthly'),
 ('Developer, mobile', 'Paraguay', 169264.0, 'Monthly'),
 ('Developer, mobile', 'Republic of Korea', 179578.5, 'Monthly'),
 ('Developer, back-end;System administrator', 'Spain', 194024.20408163266, 'Monthly'),
 ('Developer, back-end;Developer, front-end;Developer, full-stack', 'Switzerland', 245931.8904109589, 'Monthly'),
 ('Data or business analyst;Data scientist or machine learning specialist;Database administrator;Developer, back-end;Developer, front-end;System administrator', 'Canada', 349615.54545454547, 'Monthly'),
 ('Developer, back-end;Engineering manager', 'Norway', 475445.3846153846, 'Monthly'),
 ('Developer, full-stack;Developer, game or graphics', 'Australia', 501481.9534883721, 'Monthly'),
 ('Academic researcher;Educator', 'United Kingdom', 550461.4273127753, 'Monthly'),
 ('Developer, full-stack', 'Ireland', 560608.487804878, 'Monthly'),
 ('Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer, full-stack', 'New Zealand', 660363.3333333334, 'Monthly'),
 ('Data or business analyst;Developer, desktop or enterprise applications', 'Nomadic', 663684.0, 'Monthly'),
 ('Designer;Developer, desktop or enterprise applications;Developer, full-stack;Developer, game or graphics', 'United States', 797616.9523809524, 'Monthly')]

## **Impact of gender on Salary**

In [ ]:
%%sql
select Gender, country, AVG(convertedcomp), CompFreq from survey where CompFreq = "Monthly"
group by country, CompFreq
order by AVG(convertedcomp) desc;

 * sqlite://
Done.

[('Man', 'United States', 797616.9523809524, 'Monthly'),
 ('Man', 'Nomadic', 663684.0, 'Monthly'),
 ('Man', 'New Zealand', 660363.3333333334, 'Monthly'),
 ('Man', 'Ireland', 560608.487804878, 'Monthly'),
 ('Man', 'United Kingdom', 550461.4273127753, 'Monthly'),
 ('Man', 'Australia', 501481.9534883721, 'Monthly'),
 ('Man', 'Norway', 475445.3846153846, 'Monthly'),
 ('Man', 'Canada', 349615.54545454547, 'Monthly'),
 ('Man', 'Switzerland', 245931.8904109589, 'Monthly'),
 ('Man', 'Spain', 194024.20408163266, 'Monthly'),
 ('Man', 'Republic of Korea', 179578.5, 'Monthly'),
 ('Man', 'Paraguay', 169264.0, 'Monthly'),
 ('Man', 'South Korea', 156577.14285714287, 'Monthly'),
 ('Man', 'Japan', 152685.7, 'Monthly'),
 ('Man', 'Germany', 120605.56678700361, 'Monthly'),
 ('Man', 'France', 116855.42857142857, 'Monthly'),
 ('Man', 'Italy', 111531.4491017964, 'Monthly'),
 ('Woman', 'Israel', 107927.6, 'Monthly'),
 ('Man', 'Singapore', 107352.17777777778, 'Monthly'),
 ('Man', 'Costa Rica', 104316.26666666666, 'Monthly'),
 ('Man', 'Lebanon', 100395.6, 'Monthly'),
 ('Man', 'Denmark', 98906.09523809524, 'Monthly'),
 ('Man', 'Kosovo', 92892.0, 'Monthly'),
 ('Man', 'Bahamas', 86412.0, 'Monthly'),
 ('Woman', 'Austria', 84007.70370370371, 'Monthly'),
 ('Man', 'Iceland', 80721.81818181818, 'Monthly'),
 ('Man', 'Netherlands', 78936.66396761134, 'Monthly'),
 ('Man', 'Portugal', 78021.78217821782, 'Monthly'),
 ('Man', 'Ecuador', 76930.73684210527, 'Monthly'),
 ('Man', 'Belgium', 75120.80597014926, 'Monthly'),
 ('Man', 'Taiwan', 74520.0, 'Monthly'),
 ('Man', 'Sweden', 72905.90277777778, 'Monthly'),
 ('Man', 'Hong Kong (S.A.R.)', 70039.30434782608, 'Monthly'),
 ('Man', 'China', 63948.0, 'Monthly'),
 ('Man', 'Finland', 63518.52, 'Monthly'),
 ('Man', 'Kuwait', 60804.0, 'Monthly'),
 ('Man', 'Zambia', 60000.0, 'Monthly'),
 ('Man', 'Malta', 59676.0, 'Monthly'),
 ('Man', 'Luxembourg', 57186.0, 'Monthly'),
 ('Man', 'Slovenia', 56128.8, 'Monthly'),
 ('Man', 'Slovakia', 55099.32203389831, 'Monthly'),
 ('Man', 'South Africa', 54255.65562913907, 'Monthly'),
 ('Man', 'El Salvador', 52400.0, 'Monthly'),
 ('Man', 'United Arab Emirates', 51728.86956521739, 'Monthly'),
 ('Man', 'Uruguay', 51613.09090909091, 'Monthly'),
 ('Man', 'Saudi Arabia', 49950.666666666664, 'Monthly'),
 ('Man', 'Zimbabwe', 47904.0, 'Monthly'),
 ('Man', 'Cyprus', 46431.0, 'Monthly'),
 ('Man', 'Malaysia', 45026.49056603773, 'Monthly'),
 ('Man', 'Thailand', 42566.72727272727, 'Monthly'),
 ('Man', 'Poland', 42487.66507177034, 'Monthly'),
 ('Woman', 'Romania', 42420.67924528302, 'Monthly'),
 ('Man', 'Lithuania', 40919.81538461539, 'Monthly'),
 ('Man', 'Czech Republic', 40270.8, 'Monthly'),
 ('Man', 'Estonia', 39441.24590163935, 'Monthly'),
 ('Man', 'Haiti', 38364.0, 'Monthly'),
 ('Man', 'Greece', 37597.166666666664, 'Monthly'),
 ('Man', 'Armenia', 36205.89473684211, 'Monthly'),
 ('Man', 'Ukraine', 34666.568181818184, 'Monthly'),
 ('Man', 'India', 34420.88947368421, 'Monthly'),
 ('Man', 'Trinidad and Tobago', 34236.0, 'Monthly'),
 ('Man', 'Latvia', 33616.58823529412, 'Monthly'),
 ('Man', 'Rwanda', 33537.6, 'Monthly'),
 ('Man', 'Croatia', 33375.51724137931, 'Monthly'),
 ('Man', 'Oman', 32708.0, 'Monthly'),
 ('Man', 'Serbia', 31723.91489361702, 'Monthly'),
 ('Man', 'Argentina', 31677.6, 'Monthly'),
 ('Woman', 'Bulgaria', 31606.5, 'Monthly'),
 ('Man', "CÃ´te d'Ivoire", 31312.0, 'Monthly'),
 ('Man', 'Russian Federation', 31028.1935483871, 'Monthly'),
 ('Man', 'Belarus', 30463.846153846152, 'Monthly'),
 ('Man', 'Hungary', 30020.492307692308, 'Monthly'),
 ('Man', 'Albania', 29536.285714285714, 'Monthly'),
 ('Woman', 'Namibia', 28560.0, 'Monthly'),
 ('.', 'Chile', 27838.372881355932, 'Monthly'),
 ('Man', 'Jordan', 27058.4, 'Monthly'),
 ('Man', 'Bosnia and Herzegovina', 26965.333333333332, 'Monthly'),
 ('Man', 'Turkey', 26269.35135135135, 'Monthly'),
 ('Man', 'Malawi', 26220.0, 'Monthly'),
 ('Man', 'Montenegro', 25944.0, 'Monthly'),
 ('Man', 'Qatar', 25364.0, 'Monthly'),
 ('Man', 'Dominican Republic', 24984.48, 'Monthly'),
 ('Man', 'Indonesia', 24902.613333333335, 'Monthly'),
 ('Man', 'Mexico', 23940.897959183672, 'Monthly'),
 ('Man', 'Uzbekistan', 23770.0, 'Monthly'),
 ('Man', 'Georgia', 22862.823529411766, 'Monthly'),
 ('Man', 'Panama', 22800.0, 'Monthly'),
 ('Man', 'Iran', 21943.481865284975, 'Monthly'),
 ('Man', 'Brazil', 21385.647819063004, 'Monthly'),
 ('Man', 'Honduras', 20718.0, 'Monthly'),
 ('Man', 'Morocco', 20703.157894736843, 'Monthly'),
 ('Man', 'Viet Nam', 18942.206896551725, 'Monthly'),
 ('Man', 'Iraq', 18722.0, 'Monthly'),
 ('Man', 'Colombia', 18492.564705882352, 'Monthly'),
 ('Man', 'Kazakhstan', 18269.052631578947, 'Monthly'),
 ('Man', 'Maldives', 18258.0, 'Monthly'),
 ('Man', 'Uganda', 17870.4, 'Monthly'),
 ('Man', 'Azerbaijan', 17833.090909090908, 'Monthly'),
 ('Man', 'Jamaica', 17736.0, 'Monthly'),
 ('Man', 'Botswana', 17403.0, 'Monthly'),
 ('Man', 'Nicaragua', 16839.272727272728, 'Monthly'),
 ('Man', 'Peru', 16616.869565217392, 'Monthly'),
 ('Man', 'Cuba', 15219.0, 'Monthly'),
 ('Man', 'Guatemala', 14979.0, 'Monthly'),
 ('Man', 'Somalia', 14400.0, 'Monthly'),
 ('Man', 'Republic of Moldova', 14345.6, 'Monthly'),
 ('Man', 'Egypt', 13819.018867924528, 'Monthly'),
 ('Man', 'Madagascar', 13689.0, 'Monthly'),
 ('Man', 'Kenya', 13236.0, 'Monthly'),
 ('Man', 'Algeria', 13018.285714285714, 'Monthly'),
 ('Man', 'Cambodia', 12948.0, 'Monthly'),
 ('Man', 'Philippines', 12918.648648648648, 'Monthly'),
 ('Man', 'Venezuela, Bolivarian Republic of...', 11300.57142857143, 'Monthly'),
 ('Man', 'Pakistan', 11106.694736842106, 'Monthly'),
 ('Man', 'Sri Lanka', 11090.88, 'Monthly'),
 ('Man', 'The former Yugoslav Republic of Macedonia', 11007.0, 'Monthly'),
 ('Man', 'United Republic of Tanzania', 10975.2, 'Monthly'),
 ('Man', 'Tunisia', 10809.882352941177, 'Monthly'),
 ('Man', 'Mauritius', 10756.0, 'Monthly'),
 ('Man', 'Bolivia', 10087.0, 'Monthly'),
 ('Man', 'Bangladesh', 9540.11009174312, 'Monthly'),
 ('Man', 'Afghanistan', 9110.666666666666, 'Monthly'),
 ('Man', 'Democratic Republic of the Congo', 9054.0, 'Monthly'),
 ('Man', 'Swaziland', 8820.0, 'Monthly'),
 ('Man', 'Nigeria', 8792.059701492537, 'Monthly'),
 ('Man', 'Bhutan', 8448.0, 'Monthly'),
 ('Man', 'Nepal', 8360.816326530612, 'Monthly'),
 ('Man', 'Togo', 7908.0, 'Monthly'),
 ('Man', 'Guinea', 7788.0, 'Monthly'),
 ('Man', 'Senegal', 7110.0, 'Monthly'),
 ('Man', 'Ghana', 6414.545454545455, 'Monthly'),
 ('Man', 'Myanmar', 6363.428571428572, 'Monthly'),
 ('Man', 'Mongolia', 6096.0, 'Monthly'),
 ('Man', 'Kyrgyzstan', 5071.2, 'Monthly'),
 ('Man', 'Syrian Arab Republic', 4833.6, 'Monthly'),
 ('Man', 'Ethiopia', 4621.2, 'Monthly'),
 ('Man', 'Cameroon', 4416.0, 'Monthly'),
 ('Man', 'Sudan', 4312.8, 'Monthly'),
 ('Man', 'Burkina Faso', 3960.0, 'Monthly'),
 ('Man', 'Brunei Darussalam', 2580.0, 'Monthly'),
 ('Man', 'Lesotho', 24.0, 'Monthly')]

## Impact of sexuality on salary

In [ ]:
%%sql
select sexuality, country, AVG(convertedcomp) from survey where CompFreq = "Monthly"
group by country
order by AVG(convertedcomp) desc;

 * sqlite://
Done.

[('Straight / Heterosexual', 'United States', 797616.9523809524),
 ('.', 'Nomadic', 663684.0),
 ('Straight / Heterosexual', 'New Zealand', 660363.3333333334),
 ('Straight / Heterosexual', 'Ireland', 560608.487804878),
 ('Straight / Heterosexual', 'United Kingdom', 550461.4273127753),
 ('Straight / Heterosexual', 'Australia', 501481.9534883721),
 ('Straight / Heterosexual', 'Norway', 475445.3846153846),
 ('Straight / Heterosexual', 'Canada', 349615.54545454547),
 ('Bisexual', 'Switzerland', 245931.8904109589),
 ('Straight / Heterosexual', 'Spain', 194024.20408163266),
 ('.', 'Republic of Korea', 179578.5),
 ('Straight / Heterosexual', 'Paraguay', 169264.0),
 ('Bisexual', 'South Korea', 156577.14285714287),
 ('Straight / Heterosexual', 'Japan', 152685.7),
 ('Straight / Heterosexual', 'Germany', 120605.56678700361),
 ('Bisexual', 'France', 116855.42857142857),
 ('Straight / Heterosexual', 'Italy', 111531.4491017964),
 ('Bisexual', 'Israel', 107927.6),
 ('Straight / Heterosexual', 'Singapore', 107352.17777777778),
 ('Straight / Heterosexual', 'Costa Rica', 104316.26666666666),
 ('Straight / Heterosexual', 'Lebanon', 100395.6),
 ('Straight / Heterosexual', 'Denmark', 98906.09523809524),
 ('Straight / Heterosexual', 'Kosovo', 92892.0),
 ('Straight / Heterosexual', 'Bahamas', 86412.0),
 ('Straight / Heterosexual', 'Austria', 84007.70370370371),
 ('Bisexual;Queer', 'Iceland', 80721.81818181818),
 ('Straight / Heterosexual', 'Netherlands', 78936.66396761134),
 ('Straight / Heterosexual', 'Portugal', 78021.78217821782),
 ('Straight / Heterosexual', 'Ecuador', 76930.73684210527),
 ('Straight / Heterosexual', 'Belgium', 75120.80597014926),
 ('Straight / Heterosexual', 'Taiwan', 74520.0),
 ('Straight / Heterosexual', 'Sweden', 72905.90277777778),
 ('Straight / Heterosexual', 'Hong Kong (S.A.R.)', 70039.30434782608),
 ('Straight / Heterosexual', 'China', 63948.0),
 ('Straight / Heterosexual', 'Finland', 63518.52),
 ('Straight / Heterosexual', 'Kuwait', 60804.0),
 ('Bisexual', 'Zambia', 60000.0),
 ('Straight / Heterosexual', 'Malta', 59676.0),
 ('Straight / Heterosexual', 'Luxembourg', 57186.0),
 ('Straight / Heterosexual', 'Slovenia', 56128.8),
 ('Straight / Heterosexual', 'Slovakia', 55099.32203389831),
 ('Straight / Heterosexual', 'South Africa', 54255.65562913907),
 ('Straight / Heterosexual', 'El Salvador', 52400.0),
 ('Straight / Heterosexual', 'United Arab Emirates', 51728.86956521739),
 ('Straight / Heterosexual', 'Uruguay', 51613.09090909091),
 ('Straight / Heterosexual', 'Saudi Arabia', 49950.666666666664),
 ('Straight / Heterosexual', 'Zimbabwe', 47904.0),
 ('Straight / Heterosexual', 'Cyprus', 46431.0),
 ('Straight / Heterosexual', 'Malaysia', 45026.49056603773),
 ('Straight / Heterosexual', 'Thailand', 42566.72727272727),
 ('Straight / Heterosexual', 'Poland', 42487.66507177034),
 ('.', 'Romania', 42420.67924528302),
 ('Straight / Heterosexual', 'Lithuania', 40919.81538461539),
 ('Straight / Heterosexual', 'Czech Republic', 40270.8),
 ('Straight / Heterosexual', 'Estonia', 39441.24590163935),
 ('Straight / Heterosexual', 'Haiti', 38364.0),
 ('Straight / Heterosexual', 'Greece', 37597.166666666664),
 ('Straight / Heterosexual', 'Armenia', 36205.89473684211),
 ('Straight / Heterosexual', 'Ukraine', 34666.568181818184),
 ('Bisexual', 'India', 34420.88947368421),
 ('Straight / Heterosexual', 'Trinidad and Tobago', 34236.0),
 ('Straight / Heterosexual', 'Latvia', 33616.58823529412),
 ('.', 'Rwanda', 33537.6),
 ('Straight / Heterosexual', 'Croatia', 33375.51724137931),
 ('.', 'Oman', 32708.0),
 ('Straight / Heterosexual', 'Serbia', 31723.91489361702),
 ('Straight / Heterosexual', 'Argentina', 31677.6),
 ('Straight / Heterosexual', 'Bulgaria', 31606.5),
 ('Straight / Heterosexual', "CÃ´te d'Ivoire", 31312.0),
 ('Straight / Heterosexual', 'Russian Federation', 31028.1935483871),
 ('Straight / Heterosexual', 'Belarus', 30463.846153846152),
 ('.', 'Hungary', 30020.492307692308),
 ('Straight / Heterosexual', 'Albania', 29536.285714285714),
 ('Straight / Heterosexual', 'Namibia', 28560.0),
 ('.', 'Chile', 27838.372881355932),
 ('.', 'Jordan', 27058.4),
 ('Straight / Heterosexual', 'Bosnia and Herzegovina', 26965.333333333332),
 ('.', 'Turkey', 26269.35135135135),
 ('Straight / Heterosexual', 'Malawi', 26220.0),
 ('Straight / Heterosexual', 'Montenegro', 25944.0),
 ('Straight / Heterosexual', 'Qatar', 25364.0),
 ('Straight / Heterosexual', 'Dominican Republic', 24984.48),
 ('Straight / Heterosexual', 'Indonesia', 24902.613333333335),
 ('Straight / Heterosexual', 'Mexico', 23940.897959183672),
 ('Straight / Heterosexual', 'Uzbekistan', 23770.0),
 ('Straight / Heterosexual', 'Georgia', 22862.823529411766),
 ('Straight / Heterosexual', 'Panama', 22800.0),
 ('.', 'Iran', 21943.481865284975),
 ('Straight / Heterosexual', 'Brazil', 21385.647819063004),
 ('Straight / Heterosexual', 'Honduras', 20718.0),
 ('Straight / Heterosexual', 'Morocco', 20703.157894736843),
 ('Straight / Heterosexual', 'Viet Nam', 18942.206896551725),
 ('Straight / Heterosexual', 'Iraq', 18722.0),
 ('Straight / Heterosexual', 'Colombia', 18492.564705882352),
 ('Straight / Heterosexual', 'Kazakhstan', 18269.052631578947),
 ('Straight / Heterosexual', 'Maldives', 18258.0),
 ('Straight / Heterosexual', 'Uganda', 17870.4),
 ('Straight / Heterosexual', 'Azerbaijan', 17833.090909090908),
 ('Straight / Heterosexual', 'Jamaica', 17736.0),
 ('Straight / Heterosexual', 'Botswana', 17403.0),
 ('.', 'Nicaragua', 16839.272727272728),
 ('Straight / Heterosexual', 'Peru', 16616.869565217392),
 ('Straight / Heterosexual', 'Cuba', 15219.0),
 ('Straight / Heterosexual', 'Guatemala', 14979.0),
 ('.', 'Somalia', 14400.0),
 ('Straight / Heterosexual', 'Republic of Moldova', 14345.6),
 ('Straight / Heterosexual', 'Egypt', 13819.018867924528),
 ('.', 'Madagascar', 13689.0),
 ('Straight / Heterosexual', 'Kenya', 13236.0),
 ('Straight / Heterosexual', 'Algeria', 13018.285714285714),
 ('.', 'Cambodia', 12948.0),
 ('Straight / Heterosexual', 'Philippines', 12918.648648648648),
 ('Gay or Lesbian', 'Venezuela, Bolivarian Republic of...', 11300.57142857143),
 ('Straight / Heterosexual', 'Pakistan', 11106.694736842106),
 ('Straight / Heterosexual', 'Sri Lanka', 11090.88),
 ('Straight / Heterosexual', 'The former Yugoslav Republic of Macedonia', 11007.0),
 ('Straight / Heterosexual', 'United Republic of Tanzania', 10975.2),
 ('Straight / Heterosexual', 'Tunisia', 10809.882352941177),
 ('Straight / Heterosexual', 'Mauritius', 10756.0),
 ('Straight / Heterosexual', 'Bolivia', 10087.0),
 ('Straight / Heterosexual', 'Bangladesh', 9540.11009174312),
 ('.', 'Afghanistan', 9110.666666666666),
 ('Straight / Heterosexual', 'Democratic Republic of the Congo', 9054.0),
 ('.', 'Swaziland', 8820.0),
 ('Straight / Heterosexual', 'Nigeria', 8792.059701492537),
 ('Straight / Heterosexual', 'Bhutan', 8448.0),
 ('Straight / Heterosexual', 'Nepal', 8360.816326530612),
 ('Straight / Heterosexual', 'Togo', 7908.0),
 ('.', 'Guinea', 7788.0),
 ('Straight / Heterosexual', 'Senegal', 7110.0),
 ('Straight / Heterosexual', 'Ghana', 6414.545454545455),
 ('Straight / Heterosexual', 'Myanmar', 6363.428571428572),
 ('Straight / Heterosexual', 'Mongolia', 6096.0),
 ('Straight / Heterosexual', 'Kyrgyzstan', 5071.2),
 ('Straight / Heterosexual', 'Syrian Arab Republic', 4833.6),
 ('Straight / Heterosexual', 'Ethiopia', 4621.2),
 ('Straight / Heterosexual', 'Cameroon', 4416.0),
 ('Straight / Heterosexual', 'Sudan', 4312.8),
 ('Bisexual', 'Burkina Faso', 3960.0),
 ('Straight / Heterosexual', 'Brunei Darussalam', 2580.0),
 ('Straight / Heterosexual', 'Lesotho', 24.0)]

## **Impact of ethnicity on salary**

In [ ]:
%%sql
select ethnicity, country, AVG(convertedcomp) from survey where CompFreq = "Monthly"
group by country
order by AVG(convertedcomp) desc;

 * sqlite://
Done.

[('White or of European descent', 'United States', 797616.9523809524),
 ('White or of European descent', 'Nomadic', 663684.0),
 ('White or of European descent', 'New Zealand', 660363.3333333334),
 ('White or of European descent', 'Ireland', 560608.487804878),
 ('White or of European descent', 'United Kingdom', 550461.4273127753),
 ('White or of European descent', 'Australia', 501481.9534883721),
 ('White or of European descent', 'Norway', 475445.3846153846),
 ('White or of European descent', 'Canada', 349615.54545454547),
 ('White or of European descent', 'Switzerland', 245931.8904109589),
 ('White or of European descent', 'Spain', 194024.20408163266),
 ('East Asian', 'Republic of Korea', 179578.5),
 ('Hispanic or Latino/a/x', 'Paraguay', 169264.0),
 ('East Asian', 'South Korea', 156577.14285714287),
 ('White or of European descent', 'Japan', 152685.7),
 ('White or of European descent', 'Germany', 120605.56678700361),
 ('White or of European descent', 'France', 116855.42857142857),
 ('White or of European descent', 'Italy', 111531.4491017964),
 ('White or of European descent', 'Israel', 107927.6),
 ('White or of European descent', 'Singapore', 107352.17777777778),
 ('Hispanic or Latino/a/x', 'Costa Rica', 104316.26666666666),
 ('Middle Eastern', 'Lebanon', 100395.6),
 ('White or of European descent', 'Denmark', 98906.09523809524),
 ('White or of European descent', 'Kosovo', 92892.0),
 ('Black or of African descent', 'Bahamas', 86412.0),
 ('White or of European descent', 'Austria', 84007.70370370371),
 ('White or of European descent', 'Iceland', 80721.81818181818),
 ('White or of European descent', 'Netherlands', 78936.66396761134),
 ('White or of European descent', 'Portugal', 78021.78217821782),
 ('Hispanic or Latino/a/x', 'Ecuador', 76930.73684210527),
 ('White or of European descent', 'Belgium', 75120.80597014926),
 ('East Asian', 'Taiwan', 74520.0),
 ('White or of European descent', 'Sweden', 72905.90277777778),
 ('East Asian', 'Hong Kong (S.A.R.)', 70039.30434782608),
 ('East Asian', 'China', 63948.0),
 ('White or of European descent', 'Finland', 63518.52),
 ('South Asian', 'Kuwait', 60804.0),
 ('Black or of African descent', 'Zambia', 60000.0),
 ('White or of European descent', 'Malta', 59676.0),
 ('White or of European descent', 'Luxembourg', 57186.0),
 ('White or of European descent', 'Slovenia', 56128.8),
 ('White or of European descent', 'Slovakia', 55099.32203389831),
 ('.', 'South Africa', 54255.65562913907),
 ('Hispanic or Latino/a/x', 'El Salvador', 52400.0),
 ('South Asian', 'United Arab Emirates', 51728.86956521739),
 ('Hispanic or Latino/a/x;White or of European descent', 'Uruguay', 51613.09090909091),
 ('Middle Eastern', 'Saudi Arabia', 49950.666666666664),
 ('Black or of African descent', 'Zimbabwe', 47904.0),
 ('Middle Eastern', 'Cyprus', 46431.0),
 ('Southeast Asian', 'Malaysia', 45026.49056603773),
 ('Southeast Asian', 'Thailand', 42566.72727272727),
 ('White or of European descent', 'Poland', 42487.66507177034),
 ('.', 'Romania', 42420.67924528302),
 ('White or of European descent', 'Lithuania', 40919.81538461539),
 ('.', 'Czech Republic', 40270.8),
 ('White or of European descent', 'Estonia', 39441.24590163935),
 ('Black or of African descent', 'Haiti', 38364.0),
 ('White or of European descent', 'Greece', 37597.166666666664),
 ('White or of European descent', 'Armenia', 36205.89473684211),
 ('White or of European descent', 'Ukraine', 34666.568181818184),
 ('South Asian', 'India', 34420.88947368421),
 ('East Asian', 'Trinidad and Tobago', 34236.0),
 ('White or of European descent', 'Latvia', 33616.58823529412),
 ('.', 'Rwanda', 33537.6),
 ('White or of European descent', 'Croatia', 33375.51724137931),
 ('.', 'Oman', 32708.0),
 ('White or of European descent', 'Serbia', 31723.91489361702),
 ('Hispanic or Latino/a/x', 'Argentina', 31677.6),
 ('White or of European descent', 'Bulgaria', 31606.5),
 ('.', "CÃ´te d'Ivoire", 31312.0),
 ('White or of European descent', 'Russian Federation', 31028.1935483871),
 ('White or of European descent', 'Belarus', 30463.846153846152),
 ('.', 'Hungary', 30020.492307692308),
 ('White or of European descent', 'Albania', 29536.285714285714),
 ('Black or of African descent', 'Namibia', 28560.0),
 ('Hispanic or Latino/a/x;White or of European descent', 'Chile', 27838.372881355932),
 ('.', 'Jordan', 27058.4),
 ('White or of European descent', 'Bosnia and Herzegovina', 26965.333333333332),
 ('.', 'Turkey', 26269.35135135135),
 ('White or of European descent', 'Malawi', 26220.0),
 ('White or of European descent', 'Montenegro', 25944.0),
 ('Middle Eastern;South Asian', 'Qatar', 25364.0),
 ('Hispanic or Latino/a/x', 'Dominican Republic', 24984.48),
 ('Southeast Asian', 'Indonesia', 24902.613333333335),
 ('Hispanic or Latino/a/x', 'Mexico', 23940.897959183672),
 ('.', 'Uzbekistan', 23770.0),
 ('White or of European descent', 'Georgia', 22862.823529411766),
 ('Hispanic or Latino/a/x', 'Panama', 22800.0),
 ('Middle Eastern', 'Iran', 21943.481865284975),
 ('White or of European descent', 'Brazil', 21385.647819063004),
 ('Hispanic or Latino/a/x;White or of European descent', 'Honduras', 20718.0),
 ('Middle Eastern;White or of European descent', 'Morocco', 20703.157894736843),
 ('Southeast Asian', 'Viet Nam', 18942.206896551725),
 ('Middle Eastern', 'Iraq', 18722.0),
 ('Hispanic or Latino/a/x', 'Colombia', 18492.564705882352),
 ('.', 'Kazakhstan', 18269.052631578947),
 ('South Asian', 'Maldives', 18258.0),
 ('Black or of African descent', 'Uganda', 17870.4),
 ('White or of European descent', 'Azerbaijan', 17833.090909090908),
 ('Black or of African descent', 'Jamaica', 17736.0),
 ('Black or of African descent', 'Botswana', 17403.0),
 ('Hispanic or Latino/a/x', 'Nicaragua', 16839.272727272728),
 ('White or of European descent', 'Peru', 16616.869565217392),
 ('White or of European descent', 'Cuba', 15219.0),
 ('Hispanic or Latino/a/x', 'Guatemala', 14979.0),
 ('Black or of African descent', 'Somalia', 14400.0),
 ('White or of European descent', 'Republic of Moldova', 14345.6),
 ('Middle Eastern', 'Egypt', 13819.018867924528),
 ('.', 'Madagascar', 13689.0),
 ('Black or of African descent', 'Kenya', 13236.0),
 ('Black or of African descent;White or of European descent;Biracial', 'Algeria', 13018.285714285714),
 ('Southeast Asian', 'Cambodia', 12948.0),
 ('East Asian;Southeast Asian', 'Philippines', 12918.648648648648),
 ('White or of European descent', 'Venezuela, Bolivarian Republic of...', 11300.57142857143),
 ('Middle Eastern', 'Pakistan', 11106.694736842106),
 ('South Asian', 'Sri Lanka', 11090.88),
 ('White or of European descent', 'The former Yugoslav Republic of Macedonia', 11007.0),
 ('Black or of African descent', 'United Republic of Tanzania', 10975.2),
 ('Black or of African descent', 'Tunisia', 10809.882352941177),
 ('Black or of African descent;South Asian', 'Mauritius', 10756.0),
 ('Hispanic or Latino/a/x', 'Bolivia', 10087.0),
 ('South Asian', 'Bangladesh', 9540.11009174312),
 ('South Asian', 'Afghanistan', 9110.666666666666),
 ('Black or of African descent', 'Democratic Republic of the Congo', 9054.0),
 ('Black or of African descent', 'Swaziland', 8820.0),
 ('Black or of African descent', 'Nigeria', 8792.059701492537),
 ('South Asian', 'Bhutan', 8448.0),
 ('East Asian;South Asian;Southeast Asian', 'Nepal', 8360.816326530612),
 ('Black or of African descent', 'Togo', 7908.0),
 ('Black or of African descent', 'Guinea', 7788.0),
 ('.', 'Senegal', 7110.0),
 ('Black or of African descent', 'Ghana', 6414.545454545455),
 ('Southeast Asian', 'Myanmar', 6363.428571428572),
 ('East Asian', 'Mongolia', 6096.0),
 ('White or of European descent', 'Kyrgyzstan', 5071.2),
 ('Middle Eastern;White or of European descent', 'Syrian Arab Republic', 4833.6),
 ('Black or of African descent', 'Ethiopia', 4621.2),
 ('Black or of African descent', 'Cameroon', 4416.0),
 ('Black or of African descent', 'Sudan', 4312.8),
 ('Black or of African descent', 'Burkina Faso', 3960.0),
 ('Southeast Asian', 'Brunei Darussalam', 2580.0),
 ('Black or of African descent', 'Lesotho', 24.0)]

## **Types of skills possesed and how it affects the salary**

In [ ]:
%%sql
select country,DatabaseWorkedWith,LanguageWorkedWith,NEWCollabToolsWorkedWith, AVG(convertedcomp) from survey where CompFreq = "Monthly"
group by country
order by AVG(convertedcomp) desc limit 15;

 * sqlite://
Done.

[('United States', '.', 'C++;HTML/CSS;JavaScript', 'Github', 797616.9523809524),
 ('Nomadic', 'Firebase;Microsoft SQL Server;MongoDB;PostgreSQL', 'C#;JavaScript;SQL;TypeScript', 'Github;Slack;Microsoft Azure', 663684.0),
 ('New Zealand', 'Microsoft SQL Server', 'C#;HTML/CSS;JavaScript', 'Github;Slack;Microsoft Teams;Google Suite (Docs, Meet, etc)', 660363.3333333334),
 ('Ireland', 'Microsoft SQL Server;MySQL;SQLite', 'Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScript;PHP;Python;SQL;TypeScript', 'Jira;Github;Microsoft Teams;Microsoft Azure;Trello', 560608.487804878),
 ('United Kingdom', '.', 'C;C++;Rust;Scala', 'Github;Slack;Microsoft Teams;Google Suite (Docs, Meet, etc)', 550461.4273127753),
 ('Australia', 'Microsoft SQL Server;SQLite', 'C#;HTML/CSS;JavaScript;Rust;TypeScript', 'Confluence;Jira;Github;Slack;Trello', 501481.9534883721),
 ('Norway', 'Elasticsearch;PostgreSQL', 'Go;Java;Kotlin;Rust;Scala', 'Confluence;Jira;Github;Slack;Trello;Google Suite (Docs, Meet, etc)', 475445.3846153846),
 ('Canada', 'MariaDB;MySQL', 'Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA', 'Github;Slack', 349615.54545454547),
 ('Switzerland', 'Oracle', 'C++;HTML/CSS;Java;JavaScript;SQL;TypeScript', 'Confluence;Jira;Github', 245931.8904109589),
 ('Spain', 'DynamoDB;MySQL;PostgreSQL;Redis;SQLite', 'C++;JavaScript', 'Github;Slack;Google Suite (Docs, Meet, etc)', 194024.20408163266),
 ('Republic of Korea', 'Firebase;Microsoft SQL Server;MongoDB;SQLite', 'Java;Kotlin;Swift', 'Github;Gitlab;Slack', 179578.5),
 ('Paraguay', '.', 'Java;JavaScript;Kotlin;Objective-C;Swift', 'Confluence;Jira;Github;Trello', 169264.0),
 ('South Korea', 'Cassandra;MySQL;Redis', 'Bash/Shell/PowerShell;Java;JavaScript;Python', 'Jira;Github', 156577.14285714287),
 ('Japan', 'Microsoft SQL Server;Redis', 'C#;HTML/CSS;JavaScript;SQL', 'Microsoft Teams;Microsoft Azure', 152685.7),
 ('Germany', 'Microsoft SQL Server', 'Bash/Shell/PowerShell;C#;JavaScript;SQL;TypeScript', 'Jira;Github;Gitlab', 120605.56678700361)]